apiVersion: v1
data:
  cluster_name: mdl-cluster
  configuration.yaml: | 
    com.instana.plugin.prometheus:
      customMetricSources:
      - url: '/actuator/prometheus/'
        metricNameIncludeRegex: '.*'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: instana-agent
    meta.helm.sh/release-namespace: instana-agent
  labels:
    app.kubernetes.io/instance: instana-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: instana-agent
    app.kubernetes.io/version: 1.2.1
    helm.sh/chart: instana-agent-1.2.1
  name: instana-agent
  namespace: instana-agent