apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeting
  name: greeting
  namespace: greeting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeting
  strategy: {}
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - image: luebken/greeting
        ports:
        - containerPort: 8080
        name: greeting
        resources: {}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeting
  name: greeting
  namespace: greeting
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: greeting
  type: LoadBalancer